import React from "react";

import {
  Target,
  BookOpen,
  Clock3,
  Database,
  CheckCircle2,
  MemoryStick,
} from "lucide-react";

const modeNames = {
  paging:
    "Paging Memory Management",

  segmentation:
    "Segmentation",

  virtual:
    "Virtual Memory",
};

export default function PagingOverview({
  mode,
}) {

  const overviewData = {

    paging: {

      aim:
        "To understand how paging divides memory into fixed-size pages and maps them into physical frames.",

      theory:
        "Paging is a memory management technique in which logical memory is divided into fixed-size pages and physical memory is divided into frames. A page table is used to map logical addresses to physical addresses, reducing external fragmentation and improving memory utilization.",

      steps: [
        "Logical memory is divided into pages.",
        "Physical memory is divided into equal-sized frames.",
        "CPU generates a logical address.",
        "Logical address is split into page number and offset.",
        "Page table maps the page number to a physical frame.",
        "Physical address is generated using frame number and offset."
      ],

      time:
        "Address Translation Complexity: O(1)",

      space:
        "O(page table size)",

      type:
        "Fixed Size Memory Allocation",

      usage:
        "Paging is widely used in modern operating systems for virtual memory management and efficient process execution.",
    },

    segmentation: {

      aim:
        "To understand how segmentation divides memory into logical segments based on program structure.",

      theory:
        "Segmentation is a memory management scheme where memory is divided into variable-sized logical segments such as code, stack, and data. Each segment has its own base address and limit, making memory organization more meaningful and modular.",

      steps: [
        "Program memory is divided into logical segments.",
        "Each segment has a base address and limit.",
        "CPU generates a logical address containing segment number and offset.",
        "Segment table stores segment mapping information.",
        "Offset is validated against segment limit.",
        "Physical address is calculated using base address and offset."
      ],

      time:
        "Address Translation Complexity: O(1)",

      space:
        "O(segment table size)",

      type:
        "Variable Size Memory Allocation",

      usage:
        "Segmentation is used for modular programming, memory protection, and sharing logical program sections.",
    },

    virtual: {

      aim:
        "To understand how virtual memory allows processes to execute beyond the limits of physical memory.",

      theory:
        "Virtual memory is a memory management technique that gives processes the illusion of large continuous memory. It uses disk space along with RAM and loads only required pages into memory, improving multitasking and efficient resource utilization.",

      steps: [
        "Process requests memory access.",
        "Virtual address is generated by CPU.",
        "Page table checks whether page exists in physical memory.",
        "If page is absent, a page fault occurs.",
        "Required page is loaded from secondary storage.",
        "Execution resumes after mapping virtual page to physical frame."
      ],

      time:
        "Page Access Complexity: O(1)",

      space:
        "O(page table + swap space)",

      type:
        "Demand Paging System",

      usage:
        "Virtual memory is used in all modern operating systems to support multitasking, large applications, and efficient memory utilization.",
    },
  };

  const data =
    overviewData[
      mode
    ];

  return (
    <section className="overview-shell">

      <div
        className="sorting-sim-title-wrap"
        style={{
          marginBottom: 20,
        }}
      >

        <div className="sorting-sim-icon">

          <MemoryStick size={18} />

        </div>

        <div>

          <h2 className="sorting-sim-title">
            Overview
          </h2>

          <p className="sorting-sim-subtitle">

            Learn the working
            principle, address
            translation process,
            and concepts of{" "}

            {
              modeNames[
                mode
              ]
            }.

          </p>

        </div>

      </div>

      <div className="overview-hero-card">

        <div className="overview-hero-header">

          <h3>

            {
              modeNames[
                mode
              ]
            }

          </h3>

          <span className="overview-badge">
            Memory Management
          </span>

        </div>

        <p className="overview-hero-text">

          {data.theory}

        </p>

      </div>

      <div className="overview-grid">

        <div className="overview-card">

          <div className="overview-card-head">

            <Target size={18} />

            <h4>
              Aim
            </h4>

          </div>

          <p>
            {data.aim}
          </p>

        </div>

        <div className="overview-card">

          <div className="overview-card-head">

            <Clock3 size={18} />

            <h4>
              Complexity
            </h4>

          </div>

          <p>
            {data.time}
          </p>

        </div>

        <div className="overview-card">

          <div className="overview-card-head">

            <Database size={18} />

            <h4>
              Space Complexity
            </h4>

          </div>

          <p>
            {data.space}
          </p>

        </div>

        <div className="overview-card">

          <div className="overview-card-head">

            <CheckCircle2
              size={18}
            />

            <h4>
              Allocation Type
            </h4>

          </div>

          <p>
            {data.type}
          </p>

        </div>

      </div>

      <div className="overview-card overview-steps-card">

        <div className="overview-card-head">

          <BookOpen size={18} />

          <h4>
            Execution Steps
          </h4>

        </div>

        <ol className="overview-steps-list">

          {data.steps.map(
            (
              step,
              index
            ) => (

              <li
                key={index}
              >

                <span className="overview-step-index">

                  {index + 1}

                </span>

                <span>
                  {step}
                </span>

              </li>
            )
          )}

        </ol>

      </div>

      <div className="overview-card">

        <div className="overview-card-head">

          <Target size={18} />

          <h4>
            Where It Is Used
          </h4>

        </div>

        <p>
          {data.usage}
        </p>

      </div>

    </section>
  );
}